// Generated by CoffeeScript 1.8.0
var fs, lysergix, tags;

fs = require('fs');

lysergix = require('lysergix');

tags = ['angry', 'love', 'confused', 'crazy', 'smug', 'surprised', 'hurt', 'sad', 'dancing', 'laughing', 'giving up', 'running', 'other actions', 'evil', 'friends', 'meh'];

module.exports = function(filename) {
  var faceRunner, makeFace, timeoutId;
  timeoutId = null;
  makeFace = function() {
    var face, newFace;
    face = lysergix.getRandomFace(tags);
    newFace = "// " + (face.description || face.tag) + "\nsay \"" + face.content + "\"\n";
    return fs.writeFile(filename, newFace, function(err) {
      if (err) {
        return console.log(err);
      }
      timeoutId = setTimeout(makeFace, 500);
    });
  };
  return faceRunner = {
    stop: function() {
      return clearTimeout(timeoutId);
    },
    start: function() {
      if (timeoutId == null) {
        return makeFace();
      }
    }
  };
};
