// Generated by CoffeeScript 1.6.3
var face, fs;

fs = require('fs');

face = require('cool-ascii-faces');

module.exports = function(filename) {
  var faceRunner, makeFace, timeoutId;
  timeoutId = null;
  makeFace = function() {
    var newFace;
    newFace = "say \"" + (face()) + "\"\n";
    return fs.writeFile(filename, newFace, function(err) {
      if (err) {
        return console.log(err);
      }
      timeoutId = setTimeout(makeFace, 1000);
    });
  };
  return faceRunner = {
    stop: function() {
      return clearTimeout(timeoutId);
    },
    start: function() {
      if (timeoutId == null) {
        return makeFace();
      }
    }
  };
};
